workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: rd_app_13_p_1 app store connect api key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.noir.scarlet99
      vars:
        XCODE_WORKSPACE: "app_rd_13_p_1.xcworkspace"
        XCODE_SCHEME: "app_rd_13_p_1"
        APP_STORE_APP_ID: 6757937669
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --ipa-directory "$CM_BUILD_OUTPUT_DIR"
    artifacts:
      - $CM_BUILD_OUTPUT_DIR/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
